repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-ruff
        args: ["--extend-ignore=E402"]
      - id: nbqa-black  # Optional, if you want black formatting too


  - repo: local
    hooks:
      - id: jupyter-nb-strip-output
        name: Strip Jupyter Notebook Output
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        language: system
        files: \.ipynb$

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
